### ISSUE TITLE
conflict with ext/seo and possibly other third-party extensions

### ISSUE THREAD

**Issue by darthnorman** [DMKEBUSINESSGMBH/typo3-mktools#23]
addExcludedParametersForCacheHash is used to exclude the 'page' parameter from cHash calculation.
Whenever this parameter is used in another extension, mktools will likely break it. Without the page parameter, cHash stays the same and TYPO3 will always render the same page. This happend with ext/seo and its XML sitemap feature, where pagination is active (1000 entries per pages are displayed).

**Comment by hannesbochmann** [comment]
The problem is solved in 10.4 and 11.5. The page parameter or better put all mktools ajax request parameters are only excluded from the chash if a ajax request is done.
