### ISSUE TITLE
Deprecate warning in RealURL XCLASS

### ISSUE THREAD

**Issue by motordigital** [DMKEBUSINESSGMBH/typo3-mktools#4]
The RealURL XCLASS generates an deprecate warning:

Deprecated: Non-static method tx_mktools_util_RealUrl::registerXclass() should not be called statically.

It's easy to fix by replacing in "ext_localconf.php" in line 44-48 the part:

if (mktools_getConf('realUrlXclass', 'FE')) {
	tx_rnbase::load('tx_mktools_util_RealUrl');
	tx_mktools_util_RealUrl::registerXclass();
}

with 

if (mktools_getConf('realUrlXclass', 'FE')) {
	tx_rnbase::load('tx_mktools_util_RealUrl');
 	$realUrlXclass = tx_rnbase::makeInstance('tx_mktools_util_RealUrl');
 	$realUrlXclass->registerXclass();
}

**Comment by motordigital** [comment]
See my fork for the commited solution: 
https://github.com/motordigital/typo3-mktools/commit/31cf209d69ffd1106191df0106e7567aaa7fe646

**Comment by hannesbochmann** [comment]
Thanks, I fixed it.
